export type HighIntentService = {
  slug: string;
  h1: string;
  seoTitle: string;
  metaDescription: string;
  localIntro: string;
  symptoms: string[];
  process: string[];
  faqs: { q: string; a: string }[];
};

const mk = (
  slug: string,
  service: string,
  intro: string,
  symptoms: string[],
  process: string[],
  faqs: { q: string; a: string }[],
): HighIntentService => ({
  slug,
  h1: `${service} in Westchester County, NY`,
  seoTitle: `${service} Westchester County, NY | Bravo Mechanical`,
  metaDescription: `${service} in Westchester County, NY by Bravo Mechanical. Licensed local HVAC technicians, fast dispatch, clear pricing, and financing options available.`,
  localIntro: intro,
  symptoms,
  process,
  faqs,
});

export const HIGH_INTENT_SERVICES: HighIntentService[] = [
  mk("ac-repair-westchester-county-ny", "AC Repair", "When your system stops cooling in July, Bravo Mechanical provides same-day AC repair across Westchester County with transparent diagnostics and no-pressure recommendations.", ["Warm air from vents or weak airflow", "AC cycles constantly or won't turn on", "Ice on refrigerant lines or water leaks", "Musty odors, loud noises, or high electric bills"], ["Confirm model/serial and system history", "Run full cooling diagnostics and airflow checks", "Provide written repair options before work", "Test system performance and document results"], [{ q: "Do you offer emergency AC repair?", a: "Yes. We dispatch for no-cool emergencies and prioritize medically sensitive households and senior residents." }, { q: "Should I repair or replace my AC?", a: "If the system is over 12-15 years old and repair cost is high, we provide side-by-side replacement options." }]),
  mk("ac-installation-westchester-county-ny", "AC Installation", "We install central AC systems sized with load calculations for Westchester homes, improving comfort, humidity control, and long-term efficiency.", ["Current AC cannot keep up on hot days", "Frequent repairs every summer", "Indoor humidity remains high", "R-22 system nearing end of life"], ["Perform room-by-room load and duct review", "Recommend right-size equipment options", "Install, commission, and verify refrigerant charge", "Register equipment and review maintenance plan"], [{ q: "How long does central AC installation take?", a: "Most change-outs are one day; duct or electrical upgrades can extend to 2-3 days." }, { q: "Do you help with rebates?", a: "Yes, we help identify utility and federal efficiency incentives where eligible." }]),
  mk("boiler-repair-westchester-county-ny", "Boiler Repair", "From no-heat calls to circulator and ignition issues, our boiler technicians restore safe, reliable heat for homes across Westchester County.", ["No heat or uneven radiator/baseboard heat", "Boiler pressure drops or relief valve leaks", "Banging, kettling, or short cycling", "Pilot/ignition failures and lockouts"], ["Safety check for gas/CO and controls", "Diagnose burners, pumps, aquastat, and venting", "Provide clear repair quote and timeline", "Restore operation and verify combustion"], [{ q: "Can you service older cast-iron boilers?", a: "Yes. We service older and high-efficiency boilers and explain realistic life expectancy." }, { q: "Is boiler short cycling serious?", a: "Yes, it can increase fuel use and damage components if ignored." }]),
  mk("boiler-installation-westchester-county-ny", "Boiler Installation", "We install high-efficiency boilers for Westchester hydronic homes with proper piping, venting, and startup combustion tuning.", ["Boiler is 20+ years old", "Rising fuel bills with uneven comfort", "Frequent winter breakdowns", "Leaking sections or failed heat exchanger"], ["Heat-loss calculation and system design", "Permit coordination and old boiler removal", "Install boiler, controls, and near-boiler piping", "Commissioning, combustion analysis, homeowner walkthrough"], [{ q: "Do you install combi boilers?", a: "Yes, when flow rate and domestic hot water demand are a good match." }, { q: "How much does boiler installation cost?", a: "Cost depends on capacity, venting route, and piping scope; we provide written estimates." }]),
  mk("furnace-repair-westchester-county-ny", "Furnace Repair", "Bravo Mechanical provides fast gas furnace diagnostics and repairs for ignition, airflow, and control issues throughout Westchester County.", ["Furnace won't ignite or blows cold air", "Short cycling or frequent reset", "Burning smell or unusual noise", "High heating bills and weak airflow"], ["Inspect safety switches and combustion", "Test igniter, flame sensor, inducer, and blower", "Quote repairs before proceeding", "Confirm temperature rise and airflow"], [{ q: "Do you repair all furnace brands?", a: "Yes, our team services major residential and light commercial furnace brands." }, { q: "Can you come after hours?", a: "Emergency heating response is available for urgent no-heat situations." }]),
  mk("furnace-installation-westchester-county-ny", "Furnace Installation", "We install high-efficiency furnaces sized for Westchester homes to deliver stable comfort, quieter operation, and lower winter utility costs.", ["System older than 15-20 years", "Frequent expensive repairs", "Uneven room temperatures", "Outdated low-efficiency unit"], ["Manual J sizing and duct assessment", "Equipment selection and financing options", "Install with code-compliant venting and gas piping", "Startup testing and thermostat optimization"], [{ q: "Is a two-stage furnace worth it?", a: "For most homes, yes - it improves comfort and efficiency versus single-stage equipment." }, { q: "Can I pair a new furnace with AC?", a: "Yes, matched systems improve reliability and seasonal efficiency." }]),
  mk("heat-pump-installation-westchester-county-ny", "Heat Pump Installation", "We design and install cold-climate heat pump systems for Westchester homes looking to reduce fossil fuel use and improve year-round comfort.", ["Interested in electrification and rebates", "High oil or gas heating costs", "Need both heating and cooling upgrade", "Uneven comfort in shoulder seasons"], ["Load calculation and electrical review", "Select cold-climate rated equipment", "Install indoor/outdoor units and controls", "Commissioning plus rebate documentation support"], [{ q: "Will a heat pump work in NY winters?", a: "Yes, cold-climate models are designed for low outdoor temperatures common in Westchester." }, { q: "Are rebates available for heat pumps?", a: "Often yes; we help identify current NYSERDA and utility programs." }]),
  mk("mini-split-installation-westchester-county-ny", "Mini-Split Installation", "Mini-split systems are ideal for Westchester homes without ductwork, additions, and room-by-room comfort control.", ["Hot or cold spots in specific rooms", "No existing ductwork", "Need quiet heating/cooling for additions", "Basement or attic comfort issues"], ["Room-by-room sizing and head placement", "Line-set routing plan for clean finish", "Install and test each indoor zone", "Demonstrate controls and maintenance basics"], [{ q: "How many heads can one mini-split support?", a: "It depends on condenser capacity and room loads; we design for balanced performance." }, { q: "Are mini-splits noisy?", a: "No, most indoor heads operate very quietly at low fan settings." }]),
  mk("emergency-hvac-repair-westchester-county-ny", "Emergency HVAC Repair", "For no-heat and no-cooling emergencies, Bravo Mechanical offers rapid dispatch HVAC repair coverage across Westchester County.", ["No heat during freezing weather", "No cooling during heat advisory periods", "Burning odors or breaker trips", "Commercial comfort outage impacting operations"], ["24/7 intake and triage", "Dispatch nearest available technician", "Safety-first diagnosis and temporary stabilization", "Permanent repair or replacement plan"], [{ q: "Do you provide weekend emergency service?", a: "Yes, emergency HVAC support is available outside normal business hours." }, { q: "What should I do before the tech arrives?", a: "Check thermostat, filter, and breakers, then shut the system down if you smell burning or gas." }]),
  mk("commercial-hvac-westchester-county-ny", "Commercial HVAC", "We provide commercial HVAC service, repair, replacement, and planned maintenance for retail, office, and multi-tenant properties across Westchester County.", ["RTU breakdowns and comfort complaints", "High tenant hot/cold call volume", "Frequent service without root-cause fixes", "Need contract maintenance and reporting"], ["Site walk and equipment inventory", "Priority issue triage and repair", "Preventive maintenance scheduling", "Asset planning for phased replacements"], [{ q: "Do you offer PM contracts?", a: "Yes. We offer quarterly and seasonal agreements with documented service reports." }, { q: "Can service be scheduled after hours?", a: "Yes, we coordinate off-hour visits to minimize business disruption." }]),
  mk("hvac-maintenance-westchester-county-ny", "HVAC Maintenance", "Our HVAC maintenance plans help Westchester homeowners reduce breakdown risk, extend equipment life, and keep warranties in good standing.", ["Repeated seasonal breakdowns", "Rising utility costs", "Dirty coils or clogged drains", "Skipped annual tune-ups"], ["Seasonal precision tune-up checklist", "Filter, coil, electrical, and safety inspection", "Identify worn components before failure", "Share maintenance report and plan next visit"], [{ q: "How often should HVAC be serviced?", a: "Twice yearly is best - spring for cooling and fall for heating." }, { q: "Does maintenance lower energy bills?", a: "In many homes, yes. Clean and tuned systems run more efficiently." }]),
  mk("indoor-air-quality-westchester-county-ny", "Indoor Air Quality Services", "We install filtration, purification, humidity control, and ventilation solutions to improve indoor air quality in Westchester County homes.", ["Allergy flare-ups indoors", "Dry winter air or summer humidity", "Dust buildup and stale odors", "Concern about airborne contaminants"], ["Home IAQ assessment and equipment review", "Recommend filtration/humidity/ventilation options", "Install and integrate with HVAC system", "Validate airflow and provide care instructions"], [{ q: "What IAQ upgrades make the biggest difference?", a: "High-MERV filtration and humidity control usually deliver the fastest comfort improvements." }, { q: "Do UV or purifier systems help?", a: "They can, when correctly sized and paired with proper filtration and airflow." }]),
];

export const getHighIntentService = (slug?: string) =>
  slug ? HIGH_INTENT_SERVICES.find((service) => service.slug === slug) : undefined;
