export type HighIntentService = {
  slug: string;
  primaryKeyword: string;
  h1: string;
  seoTitle: string;
  metaDescription: string;
  heroSubtitle: string;
  primaryCta: string;
  localOverview: string[];
  symptoms: string[];
  whatsIncluded: string[];
  process: string[];
  repairReplaceGuidance: string[];
  equipmentTypes: string[];
  propertyTypes: string[];
  faqs: { q: string; a: string }[];
  relatedLinks: { label: string; href: string }[];
  schema: {
    serviceType: string;
    emergency?: boolean;
  };
};

type ServiceInput = Omit<HighIntentService, "h1"> & { serviceName: string };

const sharedLinks = [
  { label: "Schedule service", href: "/contact" },
  { label: "View all services", href: "/services" },
  { label: "Westchester service areas", href: "/service-areas" },
  { label: "HVAC in Yonkers", href: "/service-areas/yonkers" },
  { label: "HVAC in White Plains", href: "/service-areas/white-plains" },
  { label: "Company facts", href: "/company-facts" },
];

const mk = ({ serviceName, ...input }: ServiceInput): HighIntentService => ({
  ...input,
  h1: `${serviceName} in Westchester County, NY`,
});

export const HIGH_INTENT_SERVICES: HighIntentService[] = [
  mk({
    slug: "ac-repair-westchester-county-ny",
    primaryKeyword: "AC repair Westchester County NY",
    serviceName: "AC Repair",
    seoTitle: "AC Repair Westchester County, NY | Bravo Mechanical LLC",
    metaDescription: "Need AC repair in Westchester County? Bravo Mechanical LLC diagnoses no-cool issues fast, explains options clearly, and restores comfort with licensed local technicians.",
    heroSubtitle: "No cool air, weak airflow, or rising electric bills? We diagnose the root cause and fix it without pressure tactics.",
    primaryCta: "Request AC Repair",
    localOverview: [
      "When AC systems fail in Westchester summers, comfort and indoor humidity can get out of control quickly. Bravo Mechanical LLC focuses on practical diagnostics first so homeowners understand exactly what failed, what is urgent, and what can wait.",
      "We regularly service older central AC systems, newer high-efficiency equipment, and ductless cooling. Our technicians are used to local housing stock, from pre-war homes with retrofit ductwork to newer homes with multi-zone systems.",
      "If a same-day repair is possible, we handle it on site. If replacement is the smarter long-term decision, we provide side-by-side options with no inflated claims and no rushed upsell.",
    ],
    symptoms: ["Warm air from supply vents", "Weak airflow in one or more rooms", "Short cycling or frequent breaker trips", "Frozen coil, water around air handler, or musty odors", "Unusual noise from outdoor condenser"],
    whatsIncluded: ["Full cooling performance test and static pressure check", "Refrigerant circuit and airflow diagnostics", "Clear written repair options before work begins", "Post-repair verification and thermostat calibration", "Recommendations to reduce repeat failures"],
    process: ["Confirm equipment history and comfort complaints", "Run electrical, airflow, and refrigerant diagnostics", "Present repair paths with expected outcomes", "Complete approved repair and test full cooling cycle"],
    repairReplaceGuidance: ["Repair usually makes sense when the system is under 12 years old and the failure is isolated.", "Replacement is often worth discussing when repair costs are high, the unit is near end-of-life, or efficiency is consistently poor.", "We provide repair and replacement pricing together so you can choose based on total value, not pressure."],
    equipmentTypes: ["Central air conditioners", "Ductless mini-split cooling systems", "Heat pump cooling mode", "Air handlers and evaporator coils", "Smart thermostats and zoning controls"],
    propertyTypes: ["Single-family homes", "Condominiums and townhomes", "Small multifamily properties", "Light commercial suites"],
    faqs: [
      { q: "Do you offer emergency AC repair in Westchester County?", a: "Yes. We prioritize no-cool situations, especially during high-heat periods and medically sensitive households." },
      { q: "Can you fix AC issues the same day?", a: "Many repairs are completed same day when parts are available. If not, we stabilize the system and schedule fast follow-up." },
      { q: "Do you work on all brands?", a: "We service major residential and light-commercial brands and can advise if parts availability is limited on older systems." },
    ],
    relatedLinks: [...sharedLinks, { label: "AC installation in Westchester", href: "/services/ac-installation-westchester-county-ny" }, { label: "Emergency HVAC repair", href: "/services/emergency-hvac-repair-westchester-county-ny" }],
    schema: { serviceType: "Air Conditioning Repair", emergency: true },
  }),
  mk({
    slug: "ac-installation-westchester-county-ny",
    primaryKeyword: "AC installation Westchester County NY",
    serviceName: "AC Installation",
    seoTitle: "AC Installation Westchester County, NY | Bravo Mechanical LLC",
    metaDescription: "Professional AC installation in Westchester County, NY. Bravo Mechanical LLC sizes systems correctly, installs cleanly, and delivers dependable summer comfort.",
    heroSubtitle: "Replacing an aging AC? We design right-sized cooling systems for comfort, humidity control, and long-term reliability.",
    primaryCta: "Request AC Installation Estimate",
    localOverview: ["A quality AC install starts with load calculations and duct evaluation, not guesswork. Our team designs systems that match your home and your comfort goals.", "Westchester homes range from compact condos to larger multi-story properties. We account for insulation, sun exposure, and airflow realities so you get balanced cooling instead of hot spots.", "From equipment selection to startup testing, every step is built around clear communication and clean workmanship."],
    symptoms: ["Existing AC can’t keep up on hot afternoons", "Humidity stays high indoors", "Frequent seasonal repairs", "R-22 system nearing end of life", "High summer utility bills"],
    whatsIncluded: ["Manual load calculation and duct review", "Equipment options with efficiency tradeoffs", "Code-compliant installation and refrigerant charging", "Startup commissioning and airflow verification", "Owner walkthrough for controls and filter care"],
    process: ["Site visit and system sizing", "Proposal with equipment options", "Installation and quality checks", "Final testing and handoff"],
    repairReplaceGuidance: ["If the current unit has repeated failures and major component issues, replacement can reduce risk and annual repair spend.", "If the system is still relatively new and repairable, we will tell you that directly.", "Our recommendations focus on comfort and lifecycle cost, not the biggest ticket item."],
    equipmentTypes: ["Single-stage and two-stage central AC", "Variable-speed AC systems", "Matched furnace/air handler pairings", "Ductless cooling for additions", "Smart thermostat integrations"],
    propertyTypes: ["Owner-occupied homes", "Townhomes and condos", "Property management portfolios", "Small offices"],
    faqs: [
      { q: "How long does AC installation take?", a: "Most straightforward replacements are one day. Duct or electrical upgrades can extend the timeline." },
      { q: "Do you help with rebates?", a: "Yes, when programs apply, we help you gather required documentation." },
      { q: "Can I finance a new AC system?", a: "Financing options are available for qualifying projects." },
    ],
    relatedLinks: [...sharedLinks, { label: "AC repair in Westchester", href: "/services/ac-repair-westchester-county-ny" }, { label: "HVAC maintenance plans", href: "/services/hvac-maintenance-westchester-county-ny" }],
    schema: { serviceType: "Air Conditioning Installation" },
  }),
  mk({ slug: "boiler-repair-westchester-county-ny", primaryKeyword: "boiler repair Westchester County NY", serviceName: "Boiler Repair", seoTitle: "Boiler Repair Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Fast boiler repair for Westchester County homes. We diagnose no-heat, pressure, and circulation issues with safe, reliable repairs.", heroSubtitle: "No heat, banging pipes, or pressure loss? We troubleshoot hydronic systems and restore dependable heat.", primaryCta: "Request Boiler Repair", localOverview: ["Boiler systems are common across Westchester, especially in older homes with baseboard or radiator heat. We repair both older cast-iron systems and newer high-efficiency units.", "Our approach starts with safety and combustion checks, then moves to controls, circulation, and venting diagnostics.", "You get realistic repair guidance, including whether continued repair is practical or if replacement should be planned."], symptoms: ["No heat or uneven heat", "Boiler pressure dropping", "Relief valve leaking", "Banging or kettling sounds", "Frequent lockouts"], whatsIncluded: ["Safety and combustion checks", "Control, pump, and ignition diagnostics", "Written repair scope", "System restart and operating verification"], process: ["Safety-first inspection", "Targeted component testing", "Approval before repair", "Performance verification"], repairReplaceGuidance: ["Many boiler issues are repairable when addressed early.", "If sections leak or major parts fail repeatedly on older equipment, replacement planning may be better value.", "We explain both options with expected reliability."], equipmentTypes: ["Gas boilers", "Oil boilers", "Combi boilers", "Hydronic baseboard and radiator systems"], propertyTypes: ["Single-family homes", "Older homes with radiator heat", "Multifamily heating systems"], faqs: [{ q: "Can you repair older boilers?", a: "Yes. We service older systems and explain parts availability up front." }, { q: "Is short cycling dangerous?", a: "It can strain components and increase fuel usage. It should be diagnosed promptly." }, { q: "Do you handle emergency no-heat calls?", a: "Yes, especially during freezing weather." }], relatedLinks: [...sharedLinks, { label: "Boiler installation in Westchester", href: "/services/boiler-installation-westchester-county-ny" }, { label: "Emergency HVAC repair", href: "/services/emergency-hvac-repair-westchester-county-ny" }], schema: { serviceType: "Boiler Repair", emergency: true } }),
  mk({ slug: "boiler-installation-westchester-county-ny", primaryKeyword: "boiler installation Westchester County NY", serviceName: "Boiler Installation", seoTitle: "Boiler Installation Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Need a new boiler in Westchester County? Bravo Mechanical LLC installs high-efficiency boiler systems with proper design, commissioning, and homeowner guidance.", heroSubtitle: "Upgrading an older boiler? We install dependable hydronic systems designed for comfort and fuel efficiency.", primaryCta: "Request Boiler Installation Estimate", localOverview: ["Correct boiler sizing and piping design are critical for steady comfort and long equipment life. We build systems for real-world Westchester winter loads.", "Our team handles removal, installation, control setup, and startup testing with clear communication throughout the project.", "We focus on code-compliant, serviceable installs that are easier to maintain over time."], symptoms: ["Boiler is 20+ years old", "Frequent winter breakdowns", "Rising fuel costs", "Inconsistent heat across zones", "Leaking boiler block"], whatsIncluded: ["Heat-loss calculation", "Equipment and control selection", "Old system removal and new installation", "Combustion tuning and startup", "Owner handoff and maintenance guidance"], process: ["Design and proposal", "Permit and scheduling coordination", "Installation and piping updates", "Commissioning and walkthrough"], repairReplaceGuidance: ["Replacement is usually considered when a boiler has major structural leaks or repeated expensive failures.", "If repair is still reasonable, we can keep the current system running while planning ahead.", "We provide options based on budget, efficiency, and expected longevity."], equipmentTypes: ["High-efficiency gas boilers", "Conventional cast-iron boilers", "Combi systems where appropriate", "Hydronic zoning controls"], propertyTypes: ["Single-family homes", "Two- and three-family homes", "Light commercial properties"], faqs: [{ q: "Do you install combi boilers?", a: "Yes, when domestic hot water demand and flow conditions are a good fit." }, { q: "How long does installation take?", a: "Most replacements take one to two days depending on piping and venting scope." }, { q: "Will you remove the old boiler?", a: "Yes. Removal and disposal are included in installation planning." }], relatedLinks: [...sharedLinks, { label: "Boiler repair in Westchester", href: "/services/boiler-repair-westchester-county-ny" }, { label: "Furnace installation in Westchester", href: "/services/furnace-installation-westchester-county-ny" }], schema: { serviceType: "Boiler Installation" } }),
  mk({ slug: "furnace-repair-westchester-county-ny", primaryKeyword: "furnace repair Westchester County NY", serviceName: "Furnace Repair", seoTitle: "Furnace Repair Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Trusted furnace repair in Westchester County, NY. We fix ignition, airflow, and safety issues for gas furnaces with transparent service recommendations.", heroSubtitle: "If your furnace is blowing cold air or cycling off too quickly, we pinpoint the issue and restore safe heat.", primaryCta: "Request Furnace Repair", localOverview: ["Gas furnace problems can escalate quickly in winter. We prioritize safe diagnostics, especially for no-heat events and ignition-related issues.", "Our technicians test critical components, airflow, and temperature rise to confirm a complete repair—not just a temporary reset.", "You receive practical options focused on reliability and operating cost."], symptoms: ["No ignition or intermittent startup", "Blowing cool air", "Short cycling", "High heating bills", "Unusual burner or blower noise"], whatsIncluded: ["Safety and combustion review", "Igniter, sensor, inducer, and blower testing", "Electrical and control diagnostics", "Performance test after repair"], process: ["Inspect and test safety controls", "Identify root cause", "Review approved repair plan", "Complete repair and verify heat delivery"], repairReplaceGuidance: ["Repairs are often worthwhile when components fail on otherwise healthy systems.", "If heat exchanger concerns or repeated major repairs exist, replacement may be safer and more economical.", "We present both paths in writing."], equipmentTypes: ["Single-stage and two-stage gas furnaces", "Variable-speed furnaces", "Hybrid furnace + heat pump systems"], propertyTypes: ["Homes", "Townhomes", "Small multifamily"], faqs: [{ q: "Do you service all furnace brands?", a: "We service most major brands commonly installed in Westchester homes." }, { q: "Do you offer emergency no-heat service?", a: "Yes, emergency support is available for urgent heating outages." }, { q: "How can I prevent repeat furnace issues?", a: "Annual maintenance, clean filters, and early diagnosis of minor symptoms help avoid major failures." }], relatedLinks: [...sharedLinks, { label: "Furnace installation in Westchester", href: "/services/furnace-installation-westchester-county-ny" }, { label: "HVAC maintenance", href: "/services/hvac-maintenance-westchester-county-ny" }], schema: { serviceType: "Furnace Repair", emergency: true } }),
  mk({ slug: "furnace-installation-westchester-county-ny", primaryKeyword: "furnace installation Westchester County NY", serviceName: "Furnace Installation", seoTitle: "Furnace Installation Westchester County, NY | Bravo Mechanical LLC", metaDescription: "High-efficiency furnace installation in Westchester County by Bravo Mechanical LLC. Proper sizing, clean installation, and dependable heating comfort.", heroSubtitle: "Upgrade to a dependable, efficient heating system with local installers who size and commission equipment correctly.", primaryCta: "Request Furnace Installation Estimate", localOverview: ["A furnace replacement should improve comfort, efficiency, and reliability—not just swap boxes. We evaluate airflow, return sizing, and thermostat performance before final recommendations.", "Westchester homes with mixed insulation levels benefit from proper staging and blower setup. We tune systems to reduce temperature swings and noise.", "Our install process is straightforward and homeowner-friendly."], symptoms: ["Existing furnace 15+ years old", "Frequent breakdowns", "Uneven heat between rooms", "Rising heating costs", "Major component failure"], whatsIncluded: ["Load and airflow assessment", "Equipment recommendation and financing guidance", "Code-compliant installation", "Startup commissioning and controls setup"], process: ["Assess current system and home load", "Choose equipment and schedule", "Install and test", "Walkthrough and maintenance guidance"], repairReplaceGuidance: ["Replacement is often more economical when major repairs stack up on older equipment.", "If repair still makes sense short term, we provide that path too.", "We help balance immediate budget and long-term operating cost."], equipmentTypes: ["80% and 90%+ AFUE gas furnaces", "Two-stage and variable-speed systems", "Matched AC and coil pairings"], propertyTypes: ["Single-family homes", "Townhomes", "Small property portfolios"], faqs: [{ q: "Can you pair a new furnace with existing AC?", a: "Sometimes, but matched systems often perform better and reduce future compatibility issues." }, { q: "How long does installation take?", a: "Most direct replacements are completed in one day." }, { q: "Do you offer financing?", a: "Yes, financing options are available for qualifying homeowners." }], relatedLinks: [...sharedLinks, { label: "Furnace repair in Westchester", href: "/services/furnace-repair-westchester-county-ny" }, { label: "AC installation in Westchester", href: "/services/ac-installation-westchester-county-ny" }], schema: { serviceType: "Furnace Installation" } }),
  mk({ slug: "heat-pump-installation-westchester-county-ny", primaryKeyword: "heat pump installation Westchester County NY", serviceName: "Heat Pump Installation", seoTitle: "Heat Pump Installation Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Cold-climate heat pump installation in Westchester County, NY. Bravo Mechanical designs efficient systems for year-round heating and cooling.", heroSubtitle: "Considering electrification? We install cold-climate heat pumps designed for Westchester winters and summer humidity.", primaryCta: "Request Heat Pump Estimate", localOverview: ["Heat pumps can provide efficient heating and cooling in one system when they are sized and commissioned correctly. We install cold-climate models suitable for local winter conditions.", "Each project includes equipment selection based on building load, distribution setup, and comfort preferences.", "We also help customers understand when hybrid approaches make the most sense."], symptoms: ["High heating fuel costs", "Aging AC and heating equipment", "Interest in electrification", "Uneven comfort in shoulder seasons"], whatsIncluded: ["Load calculation and equipment design", "Electrical requirement review", "Installation and control integration", "Commissioning for heating and cooling", "Guidance on available incentives"], process: ["Evaluate building and goals", "Recommend system configuration", "Install indoor/outdoor equipment", "Test low-temperature performance"], repairReplaceGuidance: ["Heat pump replacement discussions usually happen when dual-fuel strategy, efficiency goals, or aging equipment align.", "We compare projected operating cost with your current setup.", "If current equipment is still healthy, we can phase upgrades over time."], equipmentTypes: ["Cold-climate central heat pumps", "Ducted air handlers", "Hybrid heat pump + furnace systems", "Ductless multi-zone systems"], propertyTypes: ["Homes", "Townhomes", "Selective light commercial"], faqs: [{ q: "Do heat pumps work in Westchester winters?", a: "Yes, cold-climate units are designed to operate in low outdoor temperatures." }, { q: "Can a heat pump replace both AC and furnace?", a: "In many homes yes, though some properties benefit from hybrid backup heat." }, { q: "Do you assist with rebates?", a: "Yes, we help identify programs and required paperwork where applicable." }], relatedLinks: [...sharedLinks, { label: "Mini-split installation", href: "/services/mini-split-installation-westchester-county-ny" }, { label: "HVAC maintenance", href: "/services/hvac-maintenance-westchester-county-ny" }], schema: { serviceType: "Heat Pump Installation" } }),
  mk({ slug: "mini-split-installation-westchester-county-ny", primaryKeyword: "mini split installation Westchester County NY", serviceName: "Mini-Split Installation", seoTitle: "Mini-Split Installation Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Ductless mini-split installation in Westchester County for additions, older homes, and room-by-room comfort control. Clean installs and professional commissioning.", heroSubtitle: "Add efficient heating and cooling without new ductwork. Ideal for additions, finished basements, and older homes.", primaryCta: "Request Mini-Split Estimate", localOverview: ["Mini-split systems are a strong fit for many Westchester properties where ductwork is limited or room-by-room control is preferred.", "We design zone layouts that balance comfort, appearance, and serviceability.", "Install quality matters. We route line sets cleanly and verify performance at each indoor head."], symptoms: ["Hot or cold rooms", "No ductwork in key spaces", "Need comfort in additions", "Basement/attic temperature issues"], whatsIncluded: ["Room-by-room load and head placement plan", "Condenser sizing and zone balance", "Line-set and drain routing", "Startup and control training"], process: ["On-site zoning assessment", "Layout and equipment proposal", "Installation and finish work", "Performance verification"], repairReplaceGuidance: ["If existing ductless equipment is older and underperforming, replacement can improve comfort and efficiency.", "When feasible, targeted repair can extend life on newer units.", "We review both approaches with expected outcomes."], equipmentTypes: ["Single-zone mini-splits", "Multi-zone mini-splits", "Wall-mounted heads", "Concealed ducted mini-split options"], propertyTypes: ["Older homes", "Additions", "Condos", "Home offices and renovated spaces"], faqs: [{ q: "Are mini-splits noisy?", a: "Most systems run very quietly, especially at lower fan settings." }, { q: "How many indoor heads do I need?", a: "It depends on room loads and usage patterns; we size each zone accordingly." }, { q: "Can mini-splits heat in winter?", a: "Yes, modern cold-climate systems provide effective heating for many applications." }], relatedLinks: [...sharedLinks, { label: "Heat pump installation", href: "/services/heat-pump-installation-westchester-county-ny" }, { label: "Indoor air quality services", href: "/services/indoor-air-quality-westchester-county-ny" }], schema: { serviceType: "Mini-Split Installation" } }),
  mk({ slug: "emergency-hvac-repair-westchester-county-ny", primaryKeyword: "emergency HVAC repair Westchester County NY", serviceName: "Emergency HVAC Repair", seoTitle: "Emergency HVAC Repair Westchester County, NY | Bravo Mechanical LLC", metaDescription: "24/7 emergency HVAC repair in Westchester County, NY. Bravo Mechanical LLC responds to urgent no-heat and no-cool calls for homes and commercial properties.", heroSubtitle: "Urgent no-heat or no-cooling issue? Call Bravo Mechanical LLC for rapid emergency response and safety-first diagnostics.", primaryCta: "Request Emergency HVAC Service", localOverview: ["Emergencies happen at the worst times. Our emergency HVAC service is built for fast triage, clear communication, and practical next steps.", "We prioritize life-safety risks, extreme-weather no-heat/no-cool calls, and operational outages for businesses.", "When parts delay a permanent fix, we explain temporary stabilization options and return plan."], symptoms: ["No heat during freezing weather", "No cooling during extreme heat", "Electrical burning smell", "System tripping breakers", "Commercial space temperature failure"], whatsIncluded: ["Emergency intake and dispatch triage", "Safety check on arrival", "Immediate diagnosis and stabilization", "Repair completion or clear follow-up plan"], process: ["Phone triage", "Rapid dispatch", "Safety-first diagnosis", "Resolution and documented recommendations"], repairReplaceGuidance: ["Emergency calls focus first on restoring safe operation.", "If major replacement is needed, we stabilize where possible and present next-day options.", "You still receive clear repair-versus-replace guidance, even during urgent calls."], equipmentTypes: ["Furnaces", "Boilers", "Central AC", "Heat pumps", "Light commercial HVAC units"], propertyTypes: ["Residential homes", "Multifamily", "Retail and office spaces"], faqs: [{ q: "Do you provide weekend emergency service?", a: "Yes, emergency dispatch is available outside normal business hours." }, { q: "What should I do before a technician arrives?", a: "Check thermostat settings and breakers. If you smell burning or gas, shut the system down and call immediately." }, { q: "Can you service commercial emergencies?", a: "Yes, we handle urgent issues for light commercial properties across Westchester." }], relatedLinks: [...sharedLinks, { label: "Dedicated emergency HVAC page", href: "/emergency-hvac-westchester" }, { label: "AC repair in Westchester", href: "/services/ac-repair-westchester-county-ny" }], schema: { serviceType: "Emergency HVAC Repair", emergency: true } }),
  mk({ slug: "commercial-hvac-westchester-county-ny", primaryKeyword: "commercial HVAC Westchester County NY", serviceName: "Commercial HVAC", seoTitle: "Commercial HVAC Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Commercial HVAC service in Westchester County, NY for offices, retail, and mixed-use properties. Repairs, replacements, and preventive maintenance plans.", heroSubtitle: "Keep tenants, staff, and customers comfortable with responsive commercial HVAC service and planned maintenance.", primaryCta: "Request Commercial HVAC Service", localOverview: ["Commercial comfort issues can impact operations and tenant satisfaction quickly. We support Westchester businesses with responsive service and practical planning.", "From rooftop units to split systems, we prioritize root-cause diagnostics and preventive work that reduces repeat calls.", "We coordinate with facility teams and property managers to keep communication clean and predictable."], symptoms: ["Frequent hot/cold complaints", "Rooftop unit failures", "Rising emergency service calls", "Inconsistent maintenance records"], whatsIncluded: ["Site walk and equipment inventory", "Targeted diagnostics and repairs", "Preventive maintenance scheduling", "Asset planning recommendations"], process: ["Assess building and system condition", "Prioritize urgent issues", "Execute repairs and PM work", "Report findings with next-step planning"], repairReplaceGuidance: ["We evaluate repair frequency, downtime impact, and unit age before recommending replacement.", "Phased replacement plans can reduce capital shock.", "Our goal is operational reliability and predictable cost."], equipmentTypes: ["Rooftop units", "Split systems", "Packaged units", "Make-up air and ventilation equipment"], propertyTypes: ["Office buildings", "Retail storefronts", "Restaurants", "Mixed-use properties"], faqs: [{ q: "Do you offer maintenance contracts?", a: "Yes, we provide scheduled maintenance plans with documented service reporting." }, { q: "Can service be done after hours?", a: "Yes, after-hours scheduling is available to minimize disruption." }, { q: "Do you support multi-site clients?", a: "Yes, we can coordinate recurring service across multiple nearby properties." }], relatedLinks: [...sharedLinks, { label: "Emergency HVAC repair", href: "/services/emergency-hvac-repair-westchester-county-ny" }, { label: "HVAC maintenance services", href: "/services/hvac-maintenance-westchester-county-ny" }], schema: { serviceType: "Commercial HVAC Services", emergency: true } }),
  mk({ slug: "hvac-maintenance-westchester-county-ny", primaryKeyword: "HVAC maintenance Westchester County NY", serviceName: "HVAC Maintenance", seoTitle: "HVAC Maintenance Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Preventive HVAC maintenance in Westchester County, NY for heating and cooling systems. Seasonal tune-ups that reduce breakdown risk and improve efficiency.", heroSubtitle: "Protect comfort and reduce surprise breakdowns with scheduled HVAC maintenance from Bravo Mechanical LLC.", primaryCta: "Request HVAC Maintenance", localOverview: ["Preventive maintenance is the easiest way to improve reliability and keep heating/cooling systems running efficiently.", "We service both residential and light commercial systems with seasonal checklists built around safety, airflow, and performance.", "Maintenance visits include clear notes so property owners understand current condition and upcoming risks."], symptoms: ["Frequent seasonal breakdowns", "Increasing utility costs", "Dirty coils or clogged drains", "Inconsistent comfort"], whatsIncluded: ["Seasonal heating/cooling tune-ups", "Electrical and safety checks", "Filter and airflow review", "Drain, coil, and control inspection", "Written condition summary"], process: ["Schedule seasonal visit", "Perform full tune-up checklist", "Identify wear items", "Review findings and next steps"], repairReplaceGuidance: ["Maintenance helps delay replacement by catching issues before major failure.", "If we find repeated high-cost risks, we provide planning guidance for replacement timelines.", "You decide based on documented condition, not guesswork."], equipmentTypes: ["Central AC systems", "Gas furnaces", "Boilers", "Heat pumps", "Mini-splits"], propertyTypes: ["Homes", "Multifamily properties", "Small commercial buildings"], faqs: [{ q: "How often should HVAC be serviced?", a: "Twice yearly is best for most systems: spring cooling tune-up and fall heating tune-up." }, { q: "Does maintenance lower bills?", a: "Clean, tuned systems generally run more efficiently and can reduce unnecessary energy use." }, { q: "Do maintenance plans include priority scheduling?", a: "Priority scheduling options are available with service plans." }], relatedLinks: [...sharedLinks, { label: "AC repair in Westchester", href: "/services/ac-repair-westchester-county-ny" }, { label: "Furnace repair in Westchester", href: "/services/furnace-repair-westchester-county-ny" }], schema: { serviceType: "HVAC Preventive Maintenance" } }),
  mk({ slug: "indoor-air-quality-westchester-county-ny", primaryKeyword: "indoor air quality Westchester County NY", serviceName: "Indoor Air Quality Services", seoTitle: "Indoor Air Quality Services Westchester County, NY | Bravo Mechanical LLC", metaDescription: "Indoor air quality services in Westchester County, NY including filtration, humidity control, ventilation, and purification solutions for healthier indoor comfort.", heroSubtitle: "Too much dust, dryness, or humidity? We design practical IAQ improvements matched to your HVAC system.", primaryCta: "Request IAQ Consultation", localOverview: ["Indoor comfort is more than temperature. Westchester homes often struggle with seasonal dryness, summer humidity, and airborne particulates.", "We recommend air quality upgrades based on your symptoms, equipment, and budget—not one-size-fits-all add-ons.", "Our team integrates IAQ solutions so they work with existing heating and cooling systems."], symptoms: ["Dust buildup", "Allergy flare-ups indoors", "Dry winter air", "Musty odors", "Persistent humidity issues"], whatsIncluded: ["Indoor comfort and airflow assessment", "Filtration and humidity recommendations", "Ventilation and purification options", "Professional installation and setup", "Operation and maintenance guidance"], process: ["Assess symptoms and current system", "Recommend targeted IAQ upgrades", "Install and integrate components", "Verify operation and educate homeowner"], repairReplaceGuidance: ["Most IAQ upgrades can be added to existing systems without full replacement.", "If airflow or equipment limitations exist, we explain what needs to be corrected first.", "We prioritize practical improvements with measurable comfort impact."], equipmentTypes: ["High-MERV media filters", "Whole-home humidifiers", "Whole-home dehumidifiers", "UV and air purification accessories", "Ventilation solutions"], propertyTypes: ["Single-family homes", "Townhomes and condos", "Small offices"], faqs: [{ q: "What IAQ upgrade helps most homes first?", a: "Filtration and humidity control typically provide the most noticeable comfort improvement." }, { q: "Are UV systems always necessary?", a: "Not always. They can help specific situations but should be paired with proper filtration and airflow." }, { q: "Can IAQ upgrades help with seasonal allergies?", a: "Many customers report improved indoor comfort when filtration and humidity are properly managed." }], relatedLinks: [...sharedLinks, { label: "HVAC maintenance", href: "/services/hvac-maintenance-westchester-county-ny" }, { label: "Mini-split installation", href: "/services/mini-split-installation-westchester-county-ny" }], schema: { serviceType: "Indoor Air Quality Services" } }),
];

export const getHighIntentService = (slug?: string) =>
  slug ? HIGH_INTENT_SERVICES.find((service) => service.slug === slug) : undefined;
