import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Check } from "lucide-react";
import { createActivity, asDateTime } from "@/lib/crm";

type FollowUp = { id: string; lead_id: string | null; job_id: string | null; due_date: string; note: string; completed: boolean; leads?: { name: string } | null; jobs?: { title: string } | null };
export const CRMFollowUps = () => {
const [items,setItems]=useState<FollowUp[]>([]); const [leads,setLeads]=useState<{id:string;name:string}[]>([]); const [jobs,setJobs]=useState<{id:string;title:string}[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState({lead_id:"",job_id:"",due_date:"",note:""});
const load=async()=>{const [{data:a},{data:l},{data:j}]=await Promise.all([supabase.from("follow_ups").select("*,leads(name),jobs(title)").order("due_date"),supabase.from("leads").select("id,name"),supabase.from("jobs").select("id,title")]); setItems((a as FollowUp[])||[]); setLeads((l as any)||[]); setJobs((j as any)||[])}; useEffect(()=>{load();},[]);
const save=async()=>{await supabase.from("follow_ups").insert({lead_id:form.lead_id||null,job_id:form.job_id||null,due_date:form.due_date,note:form.note}); await createActivity("Follow-up created",{leadId:form.lead_id||null,jobId:form.job_id||null,details:form.note}); setOpen(false); load();};
const toggle=async(f:FollowUp)=>{await supabase.from("follow_ups").update({completed:!f.completed}).eq("id",f.id); await createActivity(f.completed?"Follow-up reopened":"Follow-up completed",{leadId:f.lead_id,jobId:f.job_id,details:f.note}); load();};
const grouped=useMemo(()=>{const t=new Date(); const today=t.toDateString(); return {overdue:items.filter(i=>!i.completed&&new Date(i.due_date)<t&&new Date(i.due_date).toDateString()!=today),today:items.filter(i=>!i.completed&&new Date(i.due_date).toDateString()==today),upcoming:items.filter(i=>!i.completed&&new Date(i.due_date)>t&&new Date(i.due_date).toDateString()!=today),completed:items.filter(i=>i.completed)};},[items]);
const sec=(title:string,arr:FollowUp[])=> <div className="space-y-2"><h3 className="font-semibold">{title} ({arr.length})</h3>{arr.map(f=><div key={f.id} className="border rounded p-3 flex gap-2"><button onClick={()=>toggle(f)} className="h-5 w-5 border rounded">{f.completed&&<Check className="h-3 w-3"/>}</button><div><p>{f.note}</p><p className="text-xs text-muted-foreground">{asDateTime(f.due_date)} {f.leads?.name?`• Lead: ${f.leads.name}`:""} {f.jobs?.title?`• Job: ${f.jobs.title}`:""}</p></div></div>)}</div>;
return <div className="space-y-4"><div className="flex justify-end"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="h-4 w-4 mr-1"/>Add</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>New Follow-up</DialogTitle></DialogHeader><div className="grid gap-2"><Label>Lead</Label><Select value={form.lead_id} onValueChange={v=>setForm({...form,lead_id:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{leads.map(l=><SelectItem key={l.id} value={l.id}>{l.name}</SelectItem>)}</SelectContent></Select><Label>Job</Label><Select value={form.job_id} onValueChange={v=>setForm({...form,job_id:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{jobs.map(j=><SelectItem key={j.id} value={j.id}>{j.title}</SelectItem>)}</SelectContent></Select><Label>Due</Label><Input type="datetime-local" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><Label>Note</Label><Textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><Button onClick={save}>Create</Button></div></DialogContent></Dialog></div>{sec("Overdue",grouped.overdue)}{sec("Today",grouped.today)}{sec("Upcoming",grouped.upcoming)}{sec("Completed",grouped.completed)}</div>
};